name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust Application
        run: cargo build --release
        working-directory: devops-takehome

      - name: Run Tests
        run: cargo test
        working-directory: devops-takehome

  docker_deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t anthonyezeji/rust-backend:latest .
          docker push anthonyezeji/rust-backend:latest
        working-directory: devops-takehome

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infrastructure/deployment.yaml
          kubectl apply -f infrastructure/service.yaml
        working-directory: devops-takehome
