name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build & Test Rust Application
        run: |
          cd devops-takehome
          cargo build --release
          cargo test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          cd devops-takehome
          docker build -t anthonyezeji/rust-backend .

      - name: Push Docker Image to Registry
        run: docker push anthonyezeji/rust-backend:latest

      - name: Deploy to Kubernetes
        run: |
          cd devops-takehome/infrastructure
          kubectl apply -f deployment.yaml
